export default {
  AUTH: 'auth',
  BOARDS: 'boards',
  COMMENTS: 'comments',
  CREATE: 'create',
  CREATE_USER: 'create-user',
  FOLLOW: 'follow',
  FORWARDSLASH: '/',
  INTERACT: 'interact',
  INTERACTIONS_CHECK: 'interactions-check',
  LOGIN: 'login',
  LOGOUT: 'logout',
  ME: 'me',
  PINS: 'pins',
  REFRESH_TOKEN: 'resfresh-token',
  REGISTER: 'register',
  USERS: 'users',
  USERNAME: 'username',
}
